version: '3.9'

services:
  dash:
    command: python3 prediction_page.py
    image: akraradets/ait-ml-dash:2023
    platform: linux/x86_64
    build: 
      context: .
      dockerfile: .Dockerfile
    ports:
      - 9001:80
    volumes:
      - ./app:/app
    environment:
      - HOST=0.0.0.0
      - PORT=80
